repository:
  name: EntMent
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  archived: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
features:
  issues: true
  discussions: true
