name: Feature request
description: Propose a feature
title: 'feat: '
labels: ['feature']
body:
  - type: textarea
    id: problem
    attributes: { label: Problem, description: What problem does this solve? }
  - type: textarea
    id: proposal
    attributes: { label: Proposal, description: How might we solve this? }
